SELECT b.USER_ID, b.NICKNAME,
CONCAT(b.CITY, ' ', b.STREET_ADDRESS1, ' ', b.STREET_ADDRESS2) as 전체주소,
CONCAT(LEFT(TLNO,3), '-', MID(TLNO,4,4), '-', RIGHT(TLNO,4)) as 전화번호
FROM USED_GOODS_USER b
JOIN USED_GOODS_BOARD a
ON a.WRITER_ID = b.USER_ID
GROUP BY a.WRITER_ID
HAVING COUNT(a.WRITER_ID) >= 3
ORDER BY USER_ID DESC

