SELECT a.CATEGORY,
SUM(b.SALES) as TOTAL_SALES
FROM BOOK a
JOIN BOOK_SALES b
ON a.BOOK_ID = b.BOOK_ID
WHERE b.SALES_DATE < '2022-02-01'
AND '2022-01-01' <= b.SALES_DATE
GROUP BY CATEGORY
ORDER BY CATEGORY