SELECT b.AUTHOR_ID, AUTHOR_NAME, CATEGORY, sum(SALES * PRICE) as TOTAL_SALES
from BOOK b
join BOOK_SALES bs on bs.BOOK_ID = b.BOOK_ID
join AUTHOR a on a.AUTHOR_ID = b.AUTHOR_ID
where SALES_DATE LIKE '2022-01%'
group by CATEGORY, b.AUTHOR_ID
order by AUTHOR_ID, CATEGORY DESC